### ISSUE TITLE
Delete 부분

### ISSUE THREAD

**Issue by LeeJiHun1** [ghdnjs18/SpringBoot-test#2]
삭제하는 부분에서 deleteBoard를 id 를 리턴받아도 결국 true or false 판단만 하니 boolean 값으로 넘겨주시는 게 더 좋을 것 같다.
Delete시 request데이터는 password와 id 인데 requestDto를 전부 사용해서 처리하셨다.

**Comment by ghdnjs18** [comment]
의견을 받아 수정해보겠습니다 ~
