### ISSUE TITLE
코드리뷰 - 최선강 기술 매니저

### ISSUE THREAD

**Issue by zzangoobrother** [ghdnjs18/SpringBoot-test#3]
안녕하세요. 과제 하시느라 수고하셨습니다.

전체적으로 잘 하셨습니다.

1. BoardService 에서 조회하는 메소드에 @Transactional(readOnly = true) 를 사용하시면 성능에 이점이 있습니다. 왜 성능에 이점이 있는지 한번 공부해보시면 좋습니다.
2. if else 문을 사용하셨는데 최대한 else 는 사용 안하시는게 좋습니다. 이는 객체지향 생활체조 9가지 를 보시면 좋습니다.

다음 과제도 화이팅 하세요!!!

**Comment by ghdnjs18** [comment]
네 감사합니다
